spring: 
   jackson:
      serialization:
         INDENT_OUTPUT: true
   datasource:
      url: jdbc:postgresql://localhost:5433/NostraMovie
      username: Nostra
      password: Nostra
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true 
      hikari:
          connection-timeout: 20000
          minimum-idle: 10
          maximum-pool-size: 10
          idle-timeout: 10000
          max-lifetime: 1000
          auto-commit: true
   jpa:
      database: default
      show-sql: true
      properties:
         hibernate:
            format_sql: true
      hibernate: 
#         dialect: org.hibernate.dialect.SQLServer2012Dialect
         ddl-auto: update
         
server:
   port: 8000
   
